language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
install: pip install mako coveralls testtools
script: coverage run setup.py test
after_success: coveralls
notifications:
  email:
    - dreae@dreaescantina.com
  irc:
    channels:
      -  "irc.alphachat.net#dreaescantina"